#!/usr/bin/env bash

set -e

THEME_NAME="Andromeda-custom"
DEST_DIR="$HOME/.themes/$THEME_NAME"
SRC_DIR="scss"
DIST_DIR="dist"
CONFIG_FILE="$SRC_DIR/_config.scss"
LINK_GTK4="false"
INSTALL_ICONS="false"

SHELL_BORDER="false"
WINDOW_BORDER="false"

show_help() {
    echo "Usage: ./install.sh [options]"
    echo ""
    echo "Options:"
    echo "  -sb --shell-border    Disable border for GNOME Shell panel"
    echo "  -wb --window-border   Disable border for GTK3/GTK4 windows"
    echo "  -l, --libadwaita   Link GTK4 theme directly to ~/.config/gtk-4.0"
    echo "  -i, --icons        Install custom icon pack"
    echo "  -h, --help        Show this help message"
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --shell-border|-sb) SHELL_BORDER="true"; shift ;;
        --window-border|-wb) WINDOW_BORDER="true"; shift ;;
        -l|--libadwaita) LINK_GTK4="true"; shift ;; 
        -i|--icons) INSTALL_ICONS="true"; shift ;;
        -h|--help) show_help; exit 0 ;;
        *) echo "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

echo "Generating SCSS configuration..."

rm -rf "$CONFIG_FILE"
touch "$CONFIG_FILE"

cat << EOF > "$CONFIG_FILE"
// Automatically generated by install.sh. Do not edit manually.
\$panel-border: $SHELL_BORDER;
\$window-border: $WINDOW_BORDER;
EOF

echo "Compiling SCSS stylesheets..."


rm -rf "$DIST_DIR"
mkdir "$DIST_DIR"

mkdir -p "$DIST_DIR/gtk-3.0"
mkdir -p "$DIST_DIR/gtk-4.0"
mkdir -p "$DIST_DIR/gnome-shell"

sassc "$SRC_DIR/gtk-3.0/gtk.scss" "$DIST_DIR/gtk-3.0/gtk.css" >> /dev/null
sassc "$SRC_DIR/gtk-3.0/gtk.scss" "$DIST_DIR/gtk-3.0/gtk-dark.css" >> /dev/null
sassc "$SRC_DIR/gtk-4.0/gtk.scss" "$DIST_DIR/gtk-4.0/gtk.css" >> /dev/null
sassc "$SRC_DIR/gtk-4.0/gtk.scss" "$DIST_DIR/gtk-4.0/gtk-dark.css" >> /dev/null
cp -r "$SRC_DIR/gtk-4.0/assets" "$DIST_DIR/gtk-4.0"
sassc "$SRC_DIR/gnome-shell/gnome-shell.scss" "$DIST_DIR/gnome-shell/gnome-shell.css" >> /dev/null
cp -r "$SRC_DIR/gnome-shell/assets" "$DIST_DIR/gnome-shell"

echo "Preparing destination directory..."

mkdir -p "$HOME/.themes"

if [ -d "$DEST_DIR" ]; then
    echo "Removing old theme installation at $DEST_DIR..."
    rm -rf "$DEST_DIR"
fi

mkdir -p "$DEST_DIR"

echo "Installing theme to $DEST_DIR..."

cp -r "$DIST_DIR/gtk-3.0" "$DEST_DIR/"
cp -r "$DIST_DIR/gtk-4.0" "$DEST_DIR/"
cp -r "$DIST_DIR/gnome-shell" "$DEST_DIR/"
cp -r "assets" "$DEST_DIR/"
cp -r "index.theme" "$DEST_DIR/"


if [ "$LINK_GTK4" = "true" ]; then
    echo "Linking GTK4 theme to ~/.config/gtk-4.0..."
    
    if [ -d "$HOME/.config/gtk-4.0" ] && [ ! -L "$HOME/.config/gtk-4.0" ]; then
        echo "Backing up existing gtk-4.0 config folder..."
        mv "$HOME/.config/gtk-4.0" "$HOME/.config/gtk-4.0.bak"
    fi
    
    cp -r "$DEST_DIR/gtk-4.0" "$HOME/.config/gtk-4.0"
fi

if [ "$INSTALL_ICONS" = "true" ]; then
    echo "Starting icon installation..."
    
    if [ -f "./install-icons.sh" ]; then
        chmod +x ./install-icons.sh
        
        ./install-icons.sh
    else
        echo "⚠️  Error: 'install-icons.sh' not found in the current directory!"
        exit 1
    fi
fi


echo "Installation completed successfully!"
echo "Apply your new theme using GNOME Tweaks or your system settings."